# services/orchestration-middleware-service/src/constants.py

SLOT_ID_TO_DIS_TYPE = {
    "id_card": "identity_document",
    "registration": "registration_certificate",
    "health_insurance": "health_insurance_proof",
    "pension_notice": "pension_notice",
    "stmt3": "bank_statements",
    "income": "income_declaration",
    "assets": "assets_declaration",
    "bank": "bank_details",
    "rent": "rental_contract",
    "utility_bill": "utility_cost_statement",
    "heating": "heating_costs_proof",
    "housing": "housing_costs_form",
    "household": "household_declaration",
    "cooperation_agreement": "cooperation_agreement",
}

DIS_TO_SLOT_ID_MAP = {
    "identity_document": "id_card",
    "passport": "id_card",
    "id_card": "id_card",
    "registration_certificate": "registration",
    "registration": "registration",
    "residence_permit": "registration",
    "recognition_decision": "registration",
    "asylum_stay_permit": "registration",
    "address_proof": "registration",
    "health_insurance_proof": "health_insurance",
    "health_insurance": "health_insurance",
    "pension_notice": "pension_notice",
    "pension_statement": "pension_notice",
    "private_pension_proof": "pension_notice",
    "private_pension_yearly_information": "pension_notice",
    "bank_statements": "stmt3",
    "bank_statement": "stmt3",
    "stmt3": "stmt3",
    "income_declaration": "income",
    "wage_slips": "income",
    "social_benefits_proof": "income",
    "alimony_proof": "income",
    "irregular_income_proof": "income",
    "assets_declaration": "assets",
    "savings_statements": "assets",
    "securities_statements": "assets",
    "life_insurance_contract": "assets",
    "property_ownership_proof": "assets",
    "bank_details": "bank",
    "bank": "bank",
    "rental_contract": "rent",
    "rent": "rent",
    "rent_increase_notice": "rent",
    "utility_cost_statement": "utility_bill",
    "utility_bill": "utility_bill",
    "heating_costs_proof": "heating",
    "heating_bill": "heating",
    "heating": "heating",
    "home_ownership_costs": "housing",
    "housing_costs_form": "housing",
    "household_declaration": "household",
    "cooperation_agreement": "cooperation_agreement",
}
