ALLOWED_PROFILE_FIELDS = {
    "first_name",
    "last_name",
    "date_of_birth",
    "place_of_birth",
    "legal_gender",
    "marital_status",
    "nationality",
    "second_nationality",
    "street",
    "house_number",
    "zip_code",
    "city",
    "state",
    "residence_status",
    "rent_total",
    "heating_costs",
    "hot_water_costs",
    "living_area",
    "number_of_rooms",
    "monthly_income",
    "identification_numbers",
    "social_security_no",
    "pension_insurance_no",
    "iban",
    "bank_name",
    "account_holder",
    "health_insurance_status",
    "health_insurance_provider",
    "is_main_tenant",
}

# OCR field name → profile column when names differ. Fields with the same name as a
# profile column sync automatically via the identity fallback in verified_fields.
OCR_TO_PROFILE_FIELD_MAP = {
    "given_names": "first_name",
    "family_name": "last_name",
    "birth_date": "date_of_birth",
    "birth_place": "place_of_birth",
    "city_of_birth": "place_of_birth",
    "sex": "legal_gender",
    "gender": "legal_gender",
    "street_name": "street",
    "postal_code": "zip_code",
    "monthly_total_rent": "rent_total",
    "monthly_rent": "rent_total",
    "monthly_heating_costs": "heating_costs",
    "square_meters": "living_area",
    "rooms": "number_of_rooms",
    "document_id": "identification_numbers",
    "card_number": "identification_numbers",
    "social_security_number": "pension_insurance_no",
    "pension_insurance_number": "pension_insurance_no",
    "monthly_amount": "monthly_income",
    "amount_pension": "monthly_income",
    "amount_rent": "rent_total",
    "insurance_name": "health_insurance_provider",
    "account_holder_name": "account_holder",
}

PROFILE_FIELD_TO_VALIDATOR = {
    "rent_total": "coerced_decimal",
    "heating_costs": "coerced_decimal",
    "hot_water_costs": "coerced_decimal",
    "living_area": "coerced_decimal",
    "monthly_income": "coerced_decimal",
    "number_of_rooms": "positive_integer",
    "date_of_birth": "coerced_date",
    "nationality": "CountryCode",
    "legal_gender": "Gender",
    "first_name": "non_empty_string",
    "last_name": "non_empty_string",
    "zip_code": "german_zip_code",
    "street": "non_empty_string",
    "house_number": "non_empty_string",
    "city": "non_empty_string",
    "state": "non_empty_string",
    "place_of_birth": "non_empty_string",
    "residence_status": "non_empty_string",
    "marital_status": "non_empty_string",
    "second_nationality": "CountryCode",
    "identification_numbers": "non_empty_string",
    "social_security_no": "non_empty_string",
    "pension_insurance_no": "non_empty_string",
    "iban": "non_empty_string",
    "bank_name": "non_empty_string",
    "account_holder": "non_empty_string",
    "health_insurance_status": "non_empty_string",
    "health_insurance_provider": "non_empty_string",
    "is_main_tenant": "coerced_bool",
}

ADDRESS_PROFILE_COMPONENTS = ("street", "house_number", "zip_code", "city", "state")
