# Field Mapping for antrag_bewohnerparkausweis_barrierefrei-ts.pdf
# Run './forms/scripts/validate_mappings.sh' to verify substitutions.
# Expressions wrapped in {{ }} are treated as JEXL.
# See JEXL syntax: https://commons.apache.org/proper/commons-jexl/reference/syntax.html

["p1_group3"]
type = "radio"
description = "Antrag für"
options = ["Auswahl1", "Auswahl2", "Auswahl3", "Auswahl4"]
value = ""

["p1_kennzeichen"]
type = "string"
description = "Kennzeichen"
value = ""

["p1_name_vorname"]
type = "string"
description = "Name, Vorname"
value = "{{ first_name }} {{ last_name }}"

["p1_straße_hausnummer"]
type = "string"
description = "Straße, Hausnummer"
value = ""

["p1_plz_wohnort"]
type = "string"
description = "PLZ, Wohnort"
value = ""

["p1_emailadresse"]
type = "string"
description = "E-Mail-Adresse"
value = ""

["p1_telefon"]
type = "string"
description = "Telefon"
value = ""

["p1_kennzeichen_alt"]
type = "string"
description = "Kennzeichen \\(alt\\)"
value = ""

["p2_straße_hausnummer_2"]
type = "string"
description = "Straße, Hausnummer"
value = ""

["p2_plz_wohnort_2"]
type = "string"
description = "PLZ, Wohnort"
value = ""

["p2_neu__alt"]
type = "string"
description = "neu / alt"
value = ""

["p2_group4"]
type = "radio"
description = "Zulassungsinhaber_in"
options = ["Auswahl1", "Auswahl2", "Auswahl3"]
value = ""

["p2_name_vorname_2"]
type = "string"
description = "Name, Vorname"
value = ""

["p2_straße_hausnummer_3"]
type = "string"
description = "Straße, Hausnummer"
value = ""

["p2_emailadresse_2"]
type = "string"
description = "E-Mail-Adresse"
value = ""

["p2_datum"]
type = "string"
description = "Datum"
value = ""

["p3_anmerkungen"]
type = "string"
description = "Anmerkungen"
value = ""

["p3_datum_2"]
type = "string"
description = "Datum"
value = ""

["p3_folgendes_lag_vor"]
type = "string"
description = "Folgendes lag vor:"
value = ""

["p3_check_box1"]
type = "checkbox"
description = "Folgendes_lag_vor"
value = false

["p3_check_box2"]
type = "checkbox"
description = "Folgendes_lag_vor"
value = false

["p3_check_box3"]
type = "checkbox"
description = "Folgendes_lag_vor"
value = false

["p3_check_box11"]
type = "checkbox"
description = "IchBInMitglied_CarSharing"
value = false

["p3_check_box12"]
type = "checkbox"
description = "Einverstaendnis_Melderegister"
value = false
