ALTER TABLE users ADD COLUMN IF NOT EXISTS sublet_room_count INTEGER DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS sublet_rent_income NUMERIC(10, 2) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS rent_paid_until DATE DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS landlord_name VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS heating_type VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS free_housing_right_holder VARCHAR(255) DEFAULT NULL;
