ALTER TABLE users ADD COLUMN IF NOT EXISTS monthly_income NUMERIC(10, 2);
ALTER TABLE users ADD COLUMN IF NOT EXISTS has_assets BOOLEAN;
ALTER TABLE users ADD COLUMN IF NOT EXISTS assets_description TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS income_sources JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS assets_types JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS has_costly_medical_nutrition BOOLEAN;
