apiVersion: v1
kind: Secret
metadata:
  name: authentik-certs
  namespace: default
type: Opaque
stringData:
  oidc_public.pem: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  oidc_private.pem: |
    -----BEGIN PRIVATE KEY-----
    -----END PRIVATE KEY-----
